branch-defaults:
  master:
    environment: ng-web
deploy:
  artifact: target/ng-web-0.0.1-SNAPSHOT.jar
environment-defaults:
  ng-web:
    branch: null
    repository: null
global:
  application_name: ng
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Java 8 running on
    64bit Amazon Linux/2.5.5
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
