branch-defaults:
  master:
    environment: ng-dnn
environment-defaults:
  ng-dnn:
    branch: null
    repository: null
global:
  application_name: ng-web
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.5.2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
