branch-defaults:
  default:
    environment: ng-web-dnn
global:
  application_name: ng-web
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
